version: "3.9"

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "sheduler"
      POSTGRES_USER: "django"
      POSTGRES_PASSWORD: "django"
    ports:
      - "5433:5432"

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"