# Generated by Django 4.1.3 on 2022-12-11 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheduler_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FilterTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TagForClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='distribution',
            name='filter_code',
        ),
        migrations.RemoveField(
            model_name='distribution',
            name='filter_tag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='tagforclient',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='sheduler_app.client'),
        ),
        migrations.AddField(
            model_name='filtertag',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter_tag', to='sheduler_app.distribution'),
        ),
        migrations.AddField(
            model_name='filtercode',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter_code', to='sheduler_app.distribution'),
        ),
    ]
