# Generated by Django 4.1.3 on 2022-12-11 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheduler_app', '0002_filtercode_filtertag_tagforclient_remove_client_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatorcode',
            name='code',
            field=models.IntegerField(unique=True),
        ),
    ]
