# Generated by Django 4.1.3 on 2022-12-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheduler_app', '0004_alter_client_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='timezone',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterUniqueTogether(
            name='tagforclient',
            unique_together={('client', 'name')},
        ),
    ]
